name: forge-porosity-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - notebook
  - ipykernel
  - openpyxl
  - pip
  - pip:
      - tensorflow==2.15.0
      - keras-tuner
      - lasio
      - mtpy
